### ISSUE TITLE
Lỗi - Kết quả Nội soi TMH bị đề lên kết luận

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#11]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_omon_kqtmh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019048170` - _**MaKB**_: `2211000184` - _**NgayKCB**_: `01/11/2022` - _**MaPhong**_: `10` - _**MaDV**_: `02` - _**ThangKT**_: `11` - _**NamKT**_: `2022`
   > _**MaCLS**_: `NO68` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Kết quả nội soi TMH Mô tả bệnh lý đè lên kết luận!
Tham số ha.phieuns_tmh = 1

```
Tham số sử dụng
![image](https://user-images.githubusercontent.com/96155021/199414857-d95bc9e4-58c4-441f-964b-f6a456703794.png)

KQ NS TMH
![image](https://user-images.githubusercontent.com/96155021/199415955-aaa8dd29-0389-46bc-a8a5-4192940f0de8.png)

**Comment by vinh-dh** [comment]
[Diagnose 03/11/2022](https://www.fshare.vn/file/OWACNXF3UR1I)

**Comment by le-an-87** [comment]
đã fix!
