### ISSUE TITLE
Lỗi - Sổ chẩn đoán mất cột ngày chỉ định

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#14]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `96148`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Phương Nam**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_pkpn`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Diagnose Sổ chẩn đoán hình ảnh:
 - Phiên bản ngày 05/07/2021 khi load sổ có cột: Ngày chỉ định.
thử lại tại máy thì hiển thị cột Ngày chỉ định
 - Phiên bản trước 24/05/2021 và bản 03/11/2022

```
Diagnose 05/07/2021
![image](https://user-images.githubusercontent.com/96155021/204429658-5e458e93-2add-429b-9553-0c15440a6625.png)
Diagnose 24/05/2021
![image](https://user-images.githubusercontent.com/96155021/204429727-8ce44a90-50f1-452e-bddc-a48e04f9c8f1.png)
Diagnose 03/11/2022
![image](https://user-images.githubusercontent.com/96155021/204429788-68cc84b0-597b-45f9-aea0-e94fcea02eff.png)

**Comment by vinh-dh** [comment]
[HospitalDiagnoseSetup20221129](https://www.fshare.vn/file/GWWLWKU8CSOQ)

**Comment by le-an-87** [comment]
đã bố sung!
![image](https://user-images.githubusercontent.com/96155021/204480180-8f8c07ad-3ebd-4cce-b80e-45934d046ffe.png)
