### ISSUE TITLE
Lỗi - Trả kết quả khi lưu báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#15]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `96148`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Phương Nam**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_pkpn`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000001` - _**MaKB**_: `2211014869` - _**NgayKCB**_: `30/11/2022` - _**ThangKT**_: `11` - _**NamKT**_: `2022`
   > _**MaCLS**_: `SI28`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Diagnose trả kết quả khi lưu báo lỗi!
tham số ha.gioketqua = 0

```
![image](https://user-images.githubusercontent.com/96155021/204693024-79f78748-ae74-447a-bbf3-648a7b097d45.png)

**Comment by vinh-dh** [comment]
[HospitalDiagnoseSetup20221130](https://www.fshare.vn/file/QRDB4DB5GMIE)

**Comment by le-an-87** [comment]
đã fix!
