### ISSUE TITLE
Lỗi - Sổ chẩn đoán mất cột triệu trứng

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#16]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `96148`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Phương Nam**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_pkpn`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Diagnose Sổ chẩn đoán hình ảnh:
 - Phiên bản ngày 05/07/2021 khi load sổ có cột: Triệu trứng.
thử lại tại máy thì hiển thị cột Triệu trứng (bản 30/11/2022)
```
![image](https://user-images.githubusercontent.com/96155021/204758540-fe4c68fd-30c5-48c2-b4e1-a20b0356f7c5.png)

**Comment by vinh-dh** [comment]
[HospitalDiagnoseSetup20221201](https://www.fshare.vn/file/5X3B241KHGHV)

**Comment by le-an-87** [comment]
đã bổ sung!
