### ISSUE TITLE
Lỗi - Phòng Khám Phương Nam (Sổ chẩn đoán & kết quả Siêu âm)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#17]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `96148`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Phương Nam**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phuongnam_kq2trang`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022111131` - _**MaKB**_: `2212005856` - _**NgayKCB**_: `06/12/2022` - _**MaPhong**_: `P8` - _**MaDV**_: `12` - _**ThangKT**_: `12` - _**NamKT**_: `2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI21`
   > _**ThamSo**_: `ha.phieusa` - _**Giatri**_: `1`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
1. Sổ chẩn đoán:
  -> PK đề nghị sắp xếp sổ chẩn đoán theo cột Ngày thực hiện.

2. Kết quả xem tại sổ chẩn đoán:
  - khi view kết quả thực hiện tại form sổ chẩn đoán hiển thị tiêu đề sở Y tế và tên bệnh viện không đúng.
 
3. Kết quả siêu âm mẫu ngang hiển thị 2 trang -  trang 2 không có chữ ký:
  - Kết quả siêu âm mẫu ngang in 2 trang nhưng trang 2 không có chữ ký.
  -> mẫu ngang hiện tại phần mô tả giản dòng hơi rộng. cái này anh bỏ phần giản dòng luôn được không gôm lại mẫu kết quả thành 1 trang luôn.
```
1. Sổ chẩn đoán: pk yêu cầu sắp xếp theo cột ngày thực hiện
![image](https://user-images.githubusercontent.com/96155021/206066560-1a1d0a5d-1209-48bb-967e-39df55069042.png)

2. Kết quả xem tại sổ chẩn đoán:
![image](https://user-images.githubusercontent.com/96155021/206066633-53354a8f-4d2e-4af1-aa01-550d32266080.png)

3. Kết quả siêu âm mẫu ngang hiển thị 2 trang -  trang 2 không có chữ ký:
![image](https://user-images.githubusercontent.com/96155021/206066726-659a1ed0-b0d3-45a9-b1a0-1fada37e46d9.png)
So sánh mẫu đứng(nền trắng) và mẫu ngang(nền màu xanh)
![image](https://user-images.githubusercontent.com/96155021/206067073-822672ca-7529-41f1-a598-2e5198b56c6a.png)

**Comment by vinh-dh** [comment]
[HospitalDiagnoseSetup20221207](https://www.fshare.vn/file/PRDA39RUPQ7L)

**Comment by le-an-87** [comment]
đã cập nhật!
