### ISSUE TITLE
Lỗi - PK Đông Tây: Phiếu kết quả XQ bị chồng chữ khi chẩn đoán bệnh dài

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#18]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_chandoan_xq`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `2212012836` - _**MaBA**_: `MaBA` _**NgayKCB**_: `13/12/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `12` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH338` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Chữ trên phiếu kết quả X-Quang bị chồng lên nhau khi chẩn đoán bệnh quá dài
![ảnh](https://user-images.githubusercontent.com/97272332/207203492-d321dc55-3bf4-405a-a716-457affdf7f25.png)

**Comment by chauthanhtra** [comment]
- anh kiểm tra phiếu siêu âm phần kết quả in thiếu chữ luôn nha anh
![ảnh](https://user-images.githubusercontent.com/97272332/207216801-a5d6ccc5-ba81-43d6-bf57-a0c4fcd0fc00.png)
![ảnh](https://user-images.githubusercontent.com/97272332/207216827-34498ba9-be76-4d27-b0f6-768524072479.png)

**Comment by chauthanhtra** [comment]
- Mô tả bệnh lý dài thì phần mềm không tách ra trang 2
![ảnh](https://user-images.githubusercontent.com/97272332/207224821-eae83760-1e80-4e39-b343-b342b5ecf6d0.png)
![ảnh](https://user-images.githubusercontent.com/97272332/207224867-c2b2a806-410d-4eb6-891c-5e930e9103c7.png)

**Comment by vinh-dh** [comment]
> * anh kiểm tra phiếu siêu âm phần kết quả in thiếu chữ luôn nha anh
>   ![ảnh](https://user-images.githubusercontent.com/97272332/207216801-a5d6ccc5-ba81-43d6-bf57-a0c4fcd0fc00.png)
>   ![ảnh](https://user-images.githubusercontent.com/97272332/207216827-34498ba9-be76-4d27-b0f6-768524072479.png)

Phần này là do trong ô soạn thảo (RichtextBox) chứa ký tự đặc biệt. Nó không điều khiển rớt dòng được. Nói người dùng chịu khó nhấn enter cho dòng đó tự rớt đi.

**Comment by vinh-dh** [comment]
> * Mô tả bệnh lý dài thì phần mềm không tách ra trang 2
>   ![ảnh](https://user-images.githubusercontent.com/97272332/207224821-eae83760-1e80-4e39-b343-b342b5ecf6d0.png)
>   ![ảnh](https://user-images.githubusercontent.com/97272332/207224867-c2b2a806-410d-4eb6-891c-5e930e9103c7.png)

Còn loại siêu âm tim này phải xài mẫu đặc thù mới thể hiện đầy đủ lên 1 trang được (Diagnose có phần cấu hình siêu âm tim, nói PK coi siêu âm nào phù hợp thì vào đó cấu hình), chứ mẫu đó sử dụng mà mô tả quá nhiều thì nó không thể hiện hết là phải rồi. Còn PK sử dụng mẫu đặc thù nữa thì nói PK gửi mẫu cho @nghivanbi để báo giá.

**Comment by chauthanhtra** [comment]
vậy anh fix chổ chẩn đoán này nha anh
![ảnh](https://user-images.githubusercontent.com/97272332/207250667-c9dd9598-12ee-42d8-b92a-5a57c11d43e6.png)

**Comment by vinh-dh** [comment]
> vậy anh fix chổ chẩn đoán này nha anh ![ảnh](https://user-images.githubusercontent.com/97272332/207250667-c9dd9598-12ee-42d8-b92a-5a57c11d43e6.png)

Ok

**Comment by vinh-dh** [comment]
[HospitalDiagnoseSetup20221213](https://www.fshare.vn/file/J2GVOJF7FAWD)
