### ISSUE TITLE
Yêu Cầu - PK Đông Tây: Kết luận phiếu KQ XQ không cố định ở cuỗi trang

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_chandoan_xq`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `2212012836` - _**MaBA**_: `MaBA` _**NgayKCB**_: `13/12/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `12` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH338` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Kết luận phiếu kết quả XQ không cố định ở cuối trang như phần mềm cũ
![ảnh](https://user-images.githubusercontent.com/97272332/207534800-9f166c8e-d741-4eac-baee-828c14bef30b.png)

**Comment by vinh-dh** [comment]
Sửa tiêu đề là yêu cầu nhe. Cái này không phải lỗi.

[HospitalDiagnoseSetup20221214v2](https://www.fshare.vn/file/HONXF42KIJVH)

**Comment by chauthanhtra** [comment]
Kết luận này anh nay cho nó giản ra hoặc tăng số dòng lên được không anh
hiện tại chỉ in được 1 dòng kết luận
![ảnh](https://user-images.githubusercontent.com/97272332/207552005-dde2e8d3-e2c8-412f-9b7e-7899d1285c44.png)

**Comment by vinh-dh** [comment]
[HospitalDiagnoseSetup20221215](https://www.fshare.vn/file/3C38LYU2EKF3)
