### ISSUE TITLE
Yêu cầu - PK Đông Tây: Tắt thông báo khi chỉnh bệnh lý đã cấu hình CLS mặc định

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#23]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_chandoan_xq`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- Khi chỉnh lại bệnh lý đã cấu hình CLS mặc định thì phần mềm báo CLS này chưa được cấu hình phải xoá CLS mặc định rồi chỉnh bệnh lý lưu lại, xong chọn lại bệnh lý đó chỉnh lại mới cấu hình CLS mặc định vào lại được. Phòng khám nhờ chỉnh lại để cho KTV dể sử dụng 
(có hướng dẫn chỉnh lại như vậy mà PK không chịu)

![ảnh](https://user-images.githubusercontent.com/97272332/208004522-4475a430-8fc4-4353-916d-9ff3f4184bb3.png)

**Comment by vinh-dh** [comment]
[HospitalDiagnoseSetup20221216](https://www.fshare.vn/file/3IZ8VF8L28OI)
