### ISSUE TITLE
Lỗi - Trả kết quả Citi báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#26]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_medic_miendong_full_20221216`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022099887` - _**MaKB**_: `2212007378` - _**MaBA**_: `N2022017761` _**NgayKCB**_: `19/12/2022` - _**MaPhong**_: `05` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2022`
   > _**MaCLS**_: `CH236`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi nhập kết quả cls báo lỗi:
mã bệnh lý CH22
Kết luận
{
Hiện tại chưa phát hiện tổn thương nhu mô não trên phim chụp CT Scanner.
Dày niêm mạc hàm hai bên.
Dày vẹo vách ngăn mũi sang phải. gai vách ngăn mũi phải. Khí hóa cuốn mũi giữa,phần đứng cuốn mũi giữa hai bên,phì đại cuốn mũi dưới  trái. Bít tắc nghách mũi giữa,nghách mũi dưới trái.
Không thấy bất thường cấu trúc,đậm độ nhu mô bán cầu đại não hai bên. Bít tắc nghách mũi giữa,nghách mũi dưới trái.
Không thấy bất thường cấu trúc,đậm độ nhu mô bán cầu đại não hai bên
}

```
Hình nhập kết quả báo lỗi
![image](https://user-images.githubusercontent.com/96155021/208380603-eb4db779-d6b1-431e-a383-5e4671451649.png)

**Comment by vinh-dh** [comment]
Tạo cấu trúc chạy câu SQL này nhé! Mở rộng cột ketluan: `ALTER TABLE current.pskhamha ALTER COLUMN ketluan TYPE TEXT;`

**Comment by le-an-87** [comment]
đã cập nhật!
