### ISSUE TITLE
Yêu cầu - PK Đông Tây: Phiếu kết quả CĐHA qua nhiều trang

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#27]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_kqsieuam`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bệnh lý của 1 số mẫu kết quả CĐHA (siêu âm) có bệnh lý quá dài bị che không in hết trên 1 trang giấy
Yêu cầu in phiếu kết quả có nhiều trang nếu không in hết trên 1 trang (có số trang nếu nhiều trang) phần in thiếu được đẩy qua bên phải đẩy hình ảnh kết luận xuống, phòng khám đang sử dụng mẫu siêu âm in A4 ngang, 
Hình kết quả bệnh nhân siêu âm thai ngày 20/12/2022
![ảnh](https://user-images.githubusercontent.com/97272332/208850591-9746b4e5-f84f-4036-b9bf-6cd6982edb40.png)
![ảnh](https://user-images.githubusercontent.com/97272332/208850611-7d7619dd-2e28-492a-a44c-42760e2ff957.png)

**Comment by vinh-dh** [comment]
Mẫu ngang này thiết kế chỉ áp dụng cho kq 1 tờ duy nhất. Thông tin nhiều nó không phân trang được đâu.
