### ISSUE TITLE
Lỗi - Trả kết quả CLS tháng củ báo ngày kết quả lớn hơn ngày kết thúc

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#29]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_binhan_daigngaycu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022042103` - _**MaKB**_: `2212001762` - _**NgayKCB**_: `05/12/2022` - _**MaPhong**_: `007` - _**MaDV**_: `007` - _**ThangKT**_: `12` - _**NamKT**_: `2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CLS0908`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Diagnose khi thực hiện trả kết quả của tháng củ báo ngày kết quả không được lớn hơn ngày kết thúc!

Trường hợp này mình mở cho người dùng chọn ngày thực hiện được không anh?
```
![image](https://user-images.githubusercontent.com/96155021/210476571-72c77a98-5bf2-4f54-87bd-b28efefafd26.png)
Không lưu được kết quả khi thực hiện cls của tháng củ
![image](https://user-images.githubusercontent.com/96155021/210476622-e4418874-cd82-471a-8bd9-6283dfad43a2.png)

**Comment by vinh-dh** [comment]
Đây không phải là lỗi nhé @le-an-87. Do PK sử dụng tham số ha.gioketqua = 1 (xem chi tiết yêu cầu tại đây #3). Khi đó thời gian 
thực hiện hiện tại vượt quá tháng làm việc của dữ liệu. Nếu cho thực hiện thì sẽ bị lệch dữ liệu tháng. Còn muốn thực hiện được mà ghi nhận ngày tùy chọn (trong tháng chỉ định) thì bật tham số ha.gioketqua = 0. Còn muốn khác nữa thì em trao đổi với @nghivanbi để ghi nhận yêu cầu bổ sung.
