### ISSUE TITLE
Yêu cầu - Diagnose ghi nhận giờ kết thúc lúc LƯU để làm ngày giờ kết quả

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitaldiagnose#3]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_diag_giokq`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Hiện tại Diag đang ghi nhận giờ bắt đầu trả kq làm giờ Kết thúc
Yêu cầu Diagnose ghi nhận giờ kết thúc lúc nhấn nút LƯU để làm ngày giờ kết quả.
```
![image](https://user-images.githubusercontent.com/98437757/187401084-1eb6ee4b-56db-46c1-bbd7-c546ba5e9c34.png)

**Comment by vinh-dh** [comment]
Cái link "Ngày thực hiện" đó @minhduc2it. Nếu muốn lấy thời gian gần nhất thì click vào đó nó sẽ lấy thời gian mới nhất từ server về trước khi lưu.

**Comment by le-an-87** [comment]
trường hợp này anh cho mặc định là giờ kết thúc được không anh @vinh-dh!

**Comment by vinh-dh** [comment]
@le-an-87 các bản cũ hồi xưa là mặc định giờ kết thúc lúc lưu đó. Những cơ sở trả kết quả đúng quy trình thì nó rất ít, đa phần là thời điểm nhập trả kết quả không phải là thời gian trả kết quả.

**Comment by nghivanbi** [comment]
Này Vinh bổ sung tham số nha, để bệnh viện nào muốn tự động thì bật tham số lên, khi này không cho thao tác vô các control ảnh hưởng thời gian. Còn không muốn tự động thì làm như hiện tại.

**Comment by vinh-dh** [comment]
Đã bổ sung tham số: [ha.gioketqua]. [Diagnose 08/09/2022](http://www.fsend.vn/download/9thfgjyLclGtmgBmBq1Vj97bc2vQoo4m)

**Comment by le-an-87** [comment]
khi tham số ha.gioketqua = 1
thực hiện cls mới thì sẽ cập nhật đúng giờ hiện tại lúc lưu
nhưng khi chỉnh cls củ thì sẽ cập nhật thành thời gian hiện tại luôn
ví dụ như bn ngày 17/8/2022 chỉnh giờ lại nhưng Diagnose sẽ cập nhật ra thời gian hiện tại 9/9/2022
![image](https://user-images.githubusercontent.com/96155021/189302475-5e791101-bf86-494b-ad43-3d8d2fff273c.png)
trường hợp này chỉnh thì mình lấy thời gian ở ngày thực hiện trên form được không anh!

**Comment by le-an-87** [comment]
Mấy trường hợp đăng nhập ngày củ để trả kết quả thì sẽ khi lưu sẽ lưu giờ hiện tại
![image](https://user-images.githubusercontent.com/96155021/189305044-ea1acf2a-1055-43c5-a0c5-5497b185d6b3.png)
![image](https://user-images.githubusercontent.com/96155021/189305241-1d7a00bb-30ed-44a8-817f-7186daf5a216.png)
Trường hợp này mình lấy giờ trên form được không anh!

**Comment by nghivanbi** [comment]
- Theo tham số khi thêm mới.
- Khi chỉnh thì theo thời gian người dùng chọn.
- Trường hợp đăng nhập ngày cũ vẫn lưu ngày hệ thống theo tham số, người dùng tự chỉnh lại nếu cần.

**Comment by vinh-dh** [comment]
[Diagnose 09/09/2022](http://www.fsend.vn/download/TVn5t_4UzFQbQASjgdYQafNprfL0C18q)

**Comment by le-an-87** [comment]
alo anh @vinh-dh cho em xin lại bản Diagnose mới nhe anh!

**Comment by vinh-dh** [comment]
[Diagnose 09/09/2022](https://www.fshare.vn/file/NH789CQB4C5D)
