### ISSUE TITLE
Yêu cầu - Bổ sung chức năng thực hiện quay video - Hoàn thành (02/01/2023)

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitaldiagnose#30]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

**Comment by nghivanbi** [comment]
![z3991655581949_5f016665363c281523f74fd7c7824c0d](https://user-images.githubusercontent.com/91751241/212790073-c81f3e6f-5098-4ab6-b157-98a5a1e6d62f.jpg)

**Comment by vinh-dh** [comment]
Nghiên cứu biết có làm được không mà hoàn thành 2/1/2023 vậy má?
