### ISSUE TITLE
Lỗi - BV Phụ Sản: Không tìm thấy Para trọng lượng thai

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/1/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_para_sieuam`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `27/01/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI58` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Mẫu thiết kế Siêu âm tim thai trang 1 không tìm thấy Para Trọng lượng thai

Mẫu mặc định trang 1 đang lấy para Xét nghiệm bất thường cho trọng lượng thai

![ảnh](https://user-images.githubusercontent.com/97272332/215923993-2599fe31-e1b4-4337-94f6-077a89ed7711.png)
![ảnh](https://user-images.githubusercontent.com/97272332/215924023-8383ae16-eccf-4066-aab7-e17bf617b3e8.png)
![ảnh](https://user-images.githubusercontent.com/97272332/215924046-a7dab7cb-8638-434c-8070-db7d12074cef.png)

**Comment by vinh-dh** [comment]
Bệnh viện cấu hình sai para rồi. Chỗ đó đúng của nó là para: [_16_tuoithai], các bạn đang chọn [_23_xetnghiembatthuong] nên nó không hiển thị lên là phải rồi.
![image](https://user-images.githubusercontent.com/112069710/215926294-068860bc-684e-4fe2-af25-244ba78a443f.png)

**Comment by vinh-dh** [comment]
Local:
- [HospitalDiagnoseSetup20230201](http://192.168.10.79:8090/Diagnose/HospitalDiagnoseSetup20230201.zip)

Fshare:
- [HospitalDiagnoseSetup20230201](https://www.fshare.vn/file/U9CO5C21O32R)

Các bước cập nhật:
- B1: Cập nhật bản HospitalDiagnoseSetup20230201.
- B2: Vào trang thiết kế (trang 1). Tại danh sách [Field list] ==> [Add Parameter]
![image](https://user-images.githubusercontent.com/112069710/215933927-fa90ca94-0aa5-45ad-bff5-959b2806169a.png)

- B3: Thêm mới parameter [_21_trongluongthai] như hình.
![image](https://user-images.githubusercontent.com/112069710/215934069-36bab89d-aa19-48e7-8cfb-af8ca76f4f63.png)

- B4: Cập nhật lại giá trị tại dòng [Trọng lượng thai] đúng với para mới thêm [_21_trongluongthai].
![image](https://user-images.githubusercontent.com/112069710/215934110-84221c16-e7fa-4a22-9892-86577ac20eff.png)
