### ISSUE TITLE
Lỗi - BV Phụ Sản: Không lưu được kết quả Sàng lọc sơ sinh

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#33]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **6/2/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_diagnose_dothinhluc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `2302003069` - _**MaBA**_: `MaBA` _**NgayKCB**_: `6/2/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `2` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DO16` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi trả kết quả SLSS lưu lại in được kết quả nhưng khi vào xem lại thì báo chưa có kết quả lưu lại thì báo đã tồn tại
- pssangloc có kết quả, chidinhcls không ghi nhận đã thực hiện và ngày kết quả

![ảnh](https://user-images.githubusercontent.com/97272332/216907235-6628add0-7f63-4d83-9add-b97f887907d6.png)
![ảnh](https://user-images.githubusercontent.com/97272332/216907257-5dd3c6c3-a879-43aa-99c3-8f32e2affc40.png)
![ảnh](https://user-images.githubusercontent.com/97272332/216907285-f48ab874-ba0e-434c-8fd4-89efb9fe81ef.png)
![ảnh](https://user-images.githubusercontent.com/97272332/216907319-885d839e-4680-49b3-92ad-662fd080e0f1.png)
![ảnh](https://user-images.githubusercontent.com/97272332/216907347-262cc281-29f9-4a2b-9918-e6eb4b82cd84.png)

**Comment by vinh-dh** [comment]
Local:
- [HospitalDiagnoseSetup20230207](http://192.168.10.79:8090/Diagnose/HospitalDiagnoseSetup20230207.zip)

Fshare:
- [HospitalDiagnoseSetup20230207](https://www.fshare.vn/file/3P2US9IK16GK)
