### ISSUE TITLE
Lỗi - Không thực hiện được Citi

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitaldiagnose#34]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn BI**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77134`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA THIÊN ÂN**

![z4092618225121_d8911c8a1e83302e5a63785bc30036ef](https://user-images.githubusercontent.com/91751241/217416838-f2c08569-59a0-4c0e-8a4f-8fcab2055b5f.jpg)

**Comment by nghivanbi** [comment]
@vinh-dh check lại mở ra cho Phòng khám thực hiện nhé, Ân hỗ trợ gởi Hào.

**Comment by vinh-dh** [comment]
Local:
- [HospitalDiagnoseSetup20230208](http://192.168.10.79:8090/Diagnose/HospitalDiagnoseSetup20230208.zip)

Fshare:
- [HospitalDiagnoseSetup20230208](https://www.fshare.vn/file/7D2W6R3US4UO)
