### ISSUE TITLE
Lỗi - BV Tim Mạch Cần Thơ: Chức năng lập phiếu Phẫu thuật-Thủ thuật trên Diagnose không lên sổ PT-TT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#35]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmachct_sottpt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `23000003` - _**MaKB**_: `2303001224` - _**MaBA**_: `MaBA` _**NgayKCB**_: `07/03/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `S05` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Chức năng lập phiếu PT-TT trên Diagnose ghi nhập thiếu cột tháng kế toán và năm kế toán trên bảng phauthuat nên không thống kê được trên sổ PT-TT

![ảnh](https://user-images.githubusercontent.com/97272332/223295188-faa6203c-960a-4e82-be07-a37d7d29a755.png)
![ảnh](https://user-images.githubusercontent.com/97272332/223295250-bfd2d9d3-f3ae-4ec3-a151-1332ba0020d4.png)
![ảnh](https://user-images.githubusercontent.com/97272332/223295293-d4218bf2-0180-46ae-b7d3-50448f81dcd3.png)
![ảnh](https://user-images.githubusercontent.com/97272332/223295333-3a6728b1-5eb0-4ae1-b468-f8956021d658.png)

**Comment by vinh-dh** [comment]
Nói BV cập nhật luôn Labo nhé @chauthanhtra (vì Labo chỗ sinh thiết ở BV Tim Mạch có sử dụng chức năng lập phiếu TT/PT được).

Anh có tạo script fix các ca mất `thangkt` và `namkt` trên Admin:
![image](https://user-images.githubusercontent.com/112069710/223374054-8b8b976f-5ad0-42d6-87eb-1d55512d1ec7.png)

Local:
- [HospitalDiagnoseSetup20230307](http://192.168.10.79:8090/Diagnose/HospitalDiagnoseSetup20230307.zip)
- [HospitalLaboratorySetup20230307](http://192.168.10.79:8090/Labotory/HospitalLaboratorySetup20230307.zip)

Fshare:
- [HospitalDiagnoseSetup20230307](https://www.fshare.vn/file/AYN4AU5VPP2W)
- [HospitalLaboratorySetup20230307](https://www.fshare.vn/file/2SNLPHZA7TAO)
