### ISSUE TITLE
Lỗi - chức năng hủy kết quả ( đăng nhập tài khoản admin hủy kết quả nhưng Diagnose bắt nhập tài khoản thực hiện)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#36]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ct_huykq`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `23005102` - _**MaKB**_: `2303013992` -_**NgayKCB**_: `16/03/2023` - _**MaPhong**_: `KH` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Đăng nhập tài khoản admin để thực hiện hủy kết quả cls nhưng phần mềm bắt nhập tài khoản bs thực hiện

```
thực hiện hủy kết quả
![image](https://user-images.githubusercontent.com/96155021/225572427-147ab8c2-d112-49b3-a8ea-118582e10df1.png)
bắt đăng nhập tài khoản thực hiện
![image](https://user-images.githubusercontent.com/96155021/225572576-f91d74ff-e496-41e6-818c-b0d2f04b2339.png)
Diagnose củ yêu cầu nhập mật khẩu tài khoản đăng nhập
![image](https://user-images.githubusercontent.com/96155021/225572782-ef4e40af-6a15-4e16-97c4-c77783606b2d.png)

**Comment by vinh-dh** [comment]
Local:
- [HospitalDiagnoseSetup20230317](http://192.168.10.79:8090/Diagnose/HospitalDiagnoseSetup20230317.zip)

Fshare:
- [HospitalDiagnoseSetup20230317](https://www.fshare.vn/file/C4BYN22VWPKD)

**Comment by le-an-87** [comment]
Đã fix!
