### ISSUE TITLE
Yêu cầu - Bổ sung nội dung nhật ký.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaldiagnose#37]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbnhidong_022023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại người dùng nhóm admin vào cấu hình CLS, thay đổi cấu hình chổ check "Sử dụng capture trực tiếp từ chương trình", nhật ký có lưu thao tác cấu hình nhưng không có nội dung.
Đề nghị bổ sung thêm nội dung cụ thể bỏ check hoặc check lại đối với cái Check "Sử dụng capture trực tiếp từ chương trình", vì hiện tại người quản lý không đối chiếu được với người cấu hình đó nội dung cụ thể là như thế nào.

![image](https://user-images.githubusercontent.com/99630883/228423873-4ad23e8f-21bb-45d9-9a3e-80846f5101dd.png)
![image](https://user-images.githubusercontent.com/99630883/228423949-69ae4a77-05dc-4fbe-a6ae-bbb9ac728d09.png)

**Comment by vinh-dh** [comment]
Local:
- [HospitalDiagnoseSetup20230330](http://192.168.10.79:8090/Diagnose/HospitalDiagnoseSetup20230330.zip)

Fshare:
- [HospitalDiagnoseSetup20230330](https://www.fshare.vn/file/F7DYJJPRFJ3M)
