### ISSUE TITLE
Lỗi - LỖI BẮT BUỘC ĐÓNG TIỀN CÁC CLS CÓ GIÁ 0 ĐỒNG

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitaldiagnose#41]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77155`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA ĐỒNG TÂM**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_pkdongtam_062023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI40` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Các CLS có giá tiền bằng 0 vẫn bắt buộc đóng tiền, không thể thực hiện.
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/130281806/5a2048a8-a631-4458-8cd1-b920862f4cf6)
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/130281806/a89bf689-730b-40cb-8052-351c91aab690)

**Comment by vinh-dh** [comment]
Đây không phải lỗi nhé @nqhoa1005. Vì nhiều BV hạn chế (tránh lạm dụng và tiêu cực) việc lạm dụng 0 đồng để chỉ định và thực hiện được CLS (gây thất thoát cho BV). Nên thường trước giờ các CLS này được chỉ định cũng phải qua kế toán xác nhận đã thu thì ở Diagnose mới cho thực hiện.

Cần thiết thì em lập yêu cầu mới, đề nghị bổ sung tham số cho phép thực hiện CLS có giá 0 đồng mà không bắt buộc phải thu trước khi thực hiện.

**Comment by nqhoa1005** [comment]
ok anh.
