### ISSUE TITLE
Yêu cầu - CHO PHÉP THỰC HIỆN CLS 0 ĐỒNG KHÔNG CẦN XÁC NHẬN THU TẠI KẾ TOÁN

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitaldiagnose#42]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77155`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA ĐỒNG TÂM**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_pkdongtam_062023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

khi tham số thu1lan = 1 sẽ bắt buộc đóng tiền trước mới được thực hiện CLS bao gồm các CLS có giá = 0.
> Yêu cầu bổ sung tham số cho phép thực hiện CLS có giá = 0, không cần qua thao tác tại kế toán xác nhận thu.

![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/130281806/f1af905e-5f28-4805-948f-67219a6a4dea)
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/130281806/cc62fa65-ac09-4430-91a2-a016aa03d80e)

**Comment by ongtrieuhau** [comment]
@vinh-dh hỗ trợ nhé a

**Comment by vinh-dh** [comment]
- Cập nhật cấu trúc. Bổ sung tham số: `ha.thuchien0dong`
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/33914301-4400-4b7b-a6bb-041f32339b76)

- [HospitalDiagnoseSetup20230714](https://gofile.me/78TQg/Dxqpo8oL9)
