### ISSUE TITLE
Yêu cầu - Mở chính thức hạn dùng hệ thống PACS tại BV Quận 12

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitaldiagnose#43]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN QUẬN 12 **
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hết hạn demo hệ thống PACS tại BV Quận 12, hiện tại nút PACS đang bị disable.
YC : mở chính thức sử dụng cho đơn vị

![z4482938039649_b08413cc55d998a9c48cebddfc312b05](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/130281806/c9f99e89-7ecb-4ce9-811c-7918c1beb0e1)

**Comment by nghivanbi** [comment]
Tạm mở cho bệnh viện đến ngày 31/07/2023 nhé.

**Comment by ongtrieuhau** [comment]
anh @vinh-dh xử cái này nhé a

**Comment by vinh-dh** [comment]
Đã mở tới 31/7/2023. @nqhoa1005 em nói BV tắt phần mềm rồi mở lại nhé!

**Comment by nqhoa1005** [comment]
Đã sử dụng được, em cảm ơn
