### ISSUE TITLE
Lỗi - Không hiển thị hình ảnh Điện tim trên phiếu kết quả điện tim

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#44]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **4/7/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `96148`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐK PHƯƠNG NAM**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bi_pkpn_mathinhphieudientim`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/k491LkR8f)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018126570` - _**MaKB**_: `2307002841` - _**MaBA**_: `MaBA` _**NgayKCB**_: `4/7/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `07` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DT01` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phiếu kết quả điện tim không hiển thị hình ảnh điện tim
- Phần mềm lưu được hình nhưng không load lên phiếu kết quả

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/72e7ce97-0d26-4699-aae2-0cd2c6578732)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/aa391f90-2dee-4cac-8d94-89861f45fcba)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/a94e56ab-ccf1-440d-9fe8-9c99e290dddf)

**Comment by vinh-dh** [comment]
Chỗ điện tim test của PKPN nó chỉ hiển thị và in được ảnh JPG hoặc PNG nhé @chauthanhtra. Ảnh DICOM không có in được đâu. Nên lần sau có test ảnh điện tim đừng đưa ảnh DICOM.

Còn lỗi trên để anh kiểm tra và fix lại.

**Comment by chauthanhtra** [comment]
ok anh

**Comment by vinh-dh** [comment]
- [HospitalDiagnoseSetup20230707](https://gofile.me/78TQg/jM70tIkxd)
