### ISSUE TITLE
Lỗi - Diag vào xem lại Kết quả báo CLS chưa thực hiện

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitaldiagnose#45]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_dongtay_diag`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/MjmNtQsnS

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021014714` - _**MaKB**_: `2305017175` -  _**NgayKCB**_: `17/05/2023` - _**ThangKT**_: `05` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Vào Diag xem lại Kết quả báo CLS chưa thực hiện

```
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/98437757/82e5d39c-3021-461d-8b0f-e26c03d31131)

Kiểm tra dữ liệu bảng pskhamha có dữ liệu
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/98437757/d41f81a7-4c4e-49b8-80a9-0647665fc8f5)

Bảng chidinhcls cột dath =0
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/98437757/e97a8288-b3c3-46f5-8742-a57deed15b0e)

**Comment by vinh-dh** [comment]
Để anh kiểm tra.

**Comment by vinh-dh** [comment]
- pskhamha: `ngaykcb = 17/05/2023 07:54:57`
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/7ece512b-4ad7-4c83-931b-83fdc291e941)

- chidinhcls: `ngaykcb = 17/05/2023 08:54:57`
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/1a1adda7-b6e3-4529-b40f-17be5f1695b6)

Nghĩa là trước đó `ngaykcb = 17/05/2023 07:54:57` sau đó có tác động thay đổi `ngaykcb = 17/05/2023 08:54:57` và `dath = 0`. Bất đồng bộ dữ liệu, không xác định được kết quả là đương nhiên.

**Comment by minhduc2it** [comment]
đã báo IT kiểm tra lại, có chỉnh ngày giờ khám
