### ISSUE TITLE
Lỗi - chức năng dự trù kho film X quang không load được danh mục phim xquang

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#46]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_quanngai_cnmien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Z5c9mnWu7)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**MaHH**_: `PH34` - _**ThangKT**_: `07` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng dự trù phim Xquang:
- Tiêu đề hiển thị dự trù thuốc, VTYT -> giống với tiều đề chức năng dự trù Thuốc, VTYT
- Không load được danh sách film xquang để dự trù cho kho xquang.

```
Danh mục mã hàng PH34
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/c6a467c1-b930-437e-bbd3-fee7988d2e16)
Tồn kho 14
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/1df40bc8-9529-4888-8716-4c313c43e8e0)
chức năng dự trù phim xquang không lấy được mã hàng PH34
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/c7a47c5f-ed65-497b-bb2c-32039d1d07e3)

**Comment by vinh-dh** [comment]
Ok, để anh kiểm tra.

**Comment by vinh-dh** [comment]
- [HospitalDiagnoseSetup20230727](https://gofile.me/78TQg/A5i4G8Gda)

**Comment by le-an-87** [comment]
Đã fix!
