### ISSUE TITLE
Lỗi - Phiếu kết quả không lấy được hình ảnh

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#47]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_full_16062023`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023014001` - _**MaKB**_: `2306007889` - _**NgayKCB**_: `04/08/2023` - _**ThangKT**_: `06` - _**NamKT**_: `2023`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI12`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Thực hiện trả kết quả cls SI12 có lưu hình ảnh khi lưu kết quả xong phần mềm báo ảnh kết quả của bệnh nhân không tồn tại.

```
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/230e210f-3660-4a74-a598-1ce892cde03c)

**Comment by vinh-dh** [comment]
Hình như BV đang map ổ mạng đó Ân. Phần mềm không đọc được.

**Comment by le-an-87** [comment]
bản củ được mà bản mới không được anh!

**Comment by vinh-dh** [comment]
Nói BV làm theo quy trình trước giờ của phần mềm đi. Hiện tại ổ map có thể phần mềm không hoạt động được.

**Comment by le-an-87** [comment]
ở bệnh viện trước giờ đều sử dụng như vậy.
cập nhật bản mới phần mềm báo như vậy đó anh.
vậy giờ bản mới không hỗ trợ nữa phải không anh?
để em biết em báo với bv

**Comment by vinh-dh** [comment]
Chức năng (sử dụng ổ map) trước giờ anh cũng không biết là phần mềm hoạt động được. Phần mềm cũng không thay đổi chức năng này. Do đó, việc bản mới không hoạt động được anh cũng không debug code để biết tại sao không đọc được. Để phần mềm hoạt động đúng thì nên hướng khách hàng sử dụng theo đúng quy trình trước giờ của phần mềm.

**Comment by le-an-87** [comment]
ở bv nó đã cấu hình map ổ đĩa lâu rồi và vẫn sử dụng bình thường.
hiện tại bản mới báo như vậy.
anh kêu chỉnh lại qui trình trước giờ là phải cấu hình thư mục share đúng không anh?
với anh xác định lại giùm em chổ ổ map là không hỗ trợ. để em biết đường hướng dẫn lại bệnh viện

**Comment by vinh-dh** [comment]
Em tạo môi trường test ở máy chủ công ty mình. Rồi có bị thì cung cấp lên để anh debug code coi nó bị lỗi gì? Chứ đưa chung chung, anh không thể debug code được thì đâu thể kết luận được?

**Comment by vinh-dh** [comment]
Thêm nữa là quy trình là phần mềm hướng để BV làm theo. Việc BV sử dụng theo "cách mới" không nằm trong khuyến cáo của phần mềm, giờ nó không hoạt động được rồi kết luận phần mềm không hỗ trợ là không đúng nhé!

**Comment by le-an-87** [comment]
em đâu có nói gì sai gì đâu. chỉ xác định lại chính xác để trả lời bệnh viện thôi anh!
còn chổ đó anh cần thông tin gì nữa để em cung cấp cho anh kiểm tra!

**Comment by vinh-dh** [comment]
> Em tạo môi trường test ở máy chủ công ty mình. Rồi có bị thì cung cấp lên để anh debug code coi nó bị lỗi gì? Chứ đưa chung chung, anh không thể debug code được thì đâu thể kết luận được?

Nè @le-an-87

**Comment by le-an-87** [comment]
Thông tin em có nhắn ở trên đó anh

**Comment by vinh-dh** [comment]
Anh đã search trường hợp này rồi. Kết quả là phương thức `map drive` ổ mạng nó không hỗ trợ. Nó chỉ hỗ trợ phương thức `Universal Naming Convention (UNC) ` nghĩa là sử dụng đường dẫn mạng kiểu `\\server\share\directory`.

Còn trước đó các bản cũ hoạt động được thì anh cũng không hiểu tại sao luôn. Nói chung là nói bệnh viện cấu hình lại theo phương thức `UNC` nhé!

**Comment by le-an-87** [comment]
ok để em trao đỗi với bệnh viện!
