### ISSUE TITLE
Yêu cầu - Báo cáo nhập xuất tồn kho phim không load các thuốc không có tồn + sử dụng vào báo cáo

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#5]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_nghiahanh_khophim`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Báo cáo NXT kho phim vẫn hiển thị các mã hàng không còn sử dụng nữa + không còn tồn kho
đề xuất bỏ các mặt hàng đó ra khỏi báo cáo

```
BC NXT vẫn hiển thị các mã hàng không còn sử dụng + không có tồn kho
![image](https://user-images.githubusercontent.com/96155021/188837964-f2f57fa0-b69b-4788-a067-2e9ded0c46ac.png)
![image](https://user-images.githubusercontent.com/96155021/188838009-6dff3d34-6fd2-48da-a91d-cc081cea8224.png)

BV Tồn kho không load các mã hàng này
![image](https://user-images.githubusercontent.com/96155021/188838093-0777e28a-494b-44df-b952-e683bef1eb53.png)

**Comment by vinh-dh** [comment]
Đã fix: [Diagnose 08/09/2022](http://www.fsend.vn/download/9thfgjyLclGtmgBmBq1Vj97bc2vQoo4m)

**Comment by le-an-87** [comment]
bản mới load thiếu 1 mặt hàng P82 anh ơi
![image](https://user-images.githubusercontent.com/96155021/189258750-5301267c-a0a8-4ad6-815b-2b9a2251349c.png)
![image](https://user-images.githubusercontent.com/96155021/189258773-68000424-efc8-4ef5-bde4-580fc9a95b9c.png)

**Comment by vinh-dh** [comment]
P82 là của tháng 9, hình em nói là tháng 10
![image](https://user-images.githubusercontent.com/112069710/189262293-1bffe881-d266-4482-81be-fe7c8aebd683.png)

**Comment by le-an-87** [comment]
ok sorry anh! bửa test mở tháng 10 mà em không để ý.
đã cập nhật!
