### ISSUE TITLE
Lỗi - Phiếu kết quả không lấy được hình ảnh sau khi thực hiện cls

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#50]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_thuchiencls`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000001` - _**MaKB**_: `2308006962` - _**NgayKCB**_: `22/08/2023` - _**MaPhong**_: `05` - _**MaDV**_: `07` - _**ThangKT**_: `08` - _**NamKT**_: `2023`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI63` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi thực hiện cls có chọn hình ảnh kết quả xong rồi lưu
-> phần mềm báo Ảnh kết quả bệnh nhân ... không tồn tại như hình bên dưới!
```
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/431486c6-bf7c-4185-9d8f-a2e441428fc5)

**Comment by vinh-dh** [comment]
- [HospitalDiagnoseSetup20230823](https://gofile.me/78TQg/zMZRjq1M4)

**Comment by le-an-87** [comment]
Đã fix!
