### ISSUE TITLE
Lỗi - Mất hình khi vào chọn lại hình.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaldiagnose#51]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquan12_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023067188` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023019753` _**NgayKCB**_: `28/09/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `02` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
Chú ý thông tin BN trên là BN Nội trú.

1. Sau khi chụp và chọn 6 hình, lưu xem kq in ra giấy, sau đó đóng form trả kq, vào xem thì form chụp hình bị mất hết toàn bộ hình trước đó. 
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/99630883/b083aa75-7e39-4150-8d82-a025d13f607f)
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/99630883/861ae0fa-32a7-4042-8aa7-e952216e1a21)

2.  Khi chụp hình nhưng ko xóa được 2 hình bên phải như hình dưới, có thể xóa được tất cả hình khác, riêng 2 hình bên phải sau cùng không xóa được, bắt buộc phải quay ra Bỏ qua đóng form trả kết quả rồi vào làm lại thì nó mới mất được.

![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/99630883/8e237cd6-1f6f-4063-80f8-2feaf341f870)

**Comment by vinh-dh** [comment]
- [HospitalDiagnoseSetup20230929](https://gofile.me/78TQg/kXn8d6LVx)
