### ISSUE TITLE
Lỗi - Phiếu kết quả nội soi TMH không hiển thị được kết quả nội soi (BV Hồng Ngự)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_nstmh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/bgq4xUlEe)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023034665` - _**MaKB**_: `2310005864` - _**MaBA**_: `2023016668` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `` - _**MaDV**_: `09` - _**ThangKT**_: `10` - _**NamKT**_: `2023`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `NO30` - _**PhieuYC**_: `Phiếu kết quả nội soi TMH`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Phiếu kết quả nội soi TMH không hiển thị được kết quả nội soi và các tiêu đề ký tên

```
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/151f9171-2231-44a8-bad9-972fa27778b7)

Phiếu kết quả của 1 bệnh nhân khác
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/eb41ca5a-3744-4143-a1c2-24fc818f57fc)

**Comment by vinh-dh** [comment]
Anh test thấy bình thường.
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/0ff25efa-56d6-4b02-a9b7-f5eb5b386f9e)

Theo như hình thì phiên bản đang bị là: 23/8. Em thử bản mới này coi có bị nữa không?
- File: [HospitalDiagnoseSetup20231017.zip](https://gofile.me/78TQg/kXn8d6LVx)

**Comment by le-an-87** [comment]
đã fix!
