### ISSUE TITLE
Lỗi - Diagnose vào chẩn đoán trả kết quả không load được tên bệnh nhân 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaldiagnose#53]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77156`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Phòng Khám Đa Khoa Phúc Gia Khang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphucgiakhang_xetnghiem`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023004379` - _**MaKB**_: `2312000858` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/12/2023` - _**MaPhong**_: `CLS` - _**MaDV**_: `02.03` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Bệnh nhân có chỉ định Siêu âm như hình dưới nhưng Diagnose2023.24.11 vào Chẩn đoán không thấy tên bệnh nhân

![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272364/3a8e92f4-5dc9-4988-90eb-982ee1206148)

Cấu hình cls
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272364/4eca247a-7ed3-4c28-9864-851c0dc4d64f)

![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272364/cbef2432-e2ff-40de-8004-10eafc6c67c3)

**Comment by vinh-dh** [comment]
Anh thử phiên bản 08/12 thấy bình thường @hvtuan1987 
- File: [HospitalDiagnoseSetup20231208.zip](https://gofile.me/78TQg/fojJj2ctv)
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/6a34119c-2b99-444f-8f67-b91a8a9fcd4d)

**Comment by hvtuan1987** [comment]
Dạ ok rồi áh !
