### ISSUE TITLE
Lỗi - Sổ chẩn đoán hình ảnh bị double dữ liệu bệnh nhân trả kết quả cls Xquang (BV Hồng Ngự)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#54]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_sochandoanhinhanh_19012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_hongngu_sochandoanhinhanh_19012024`](https://gofile.me/78TQg/XKE1ae6KM)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024002304` - _**MaKB**_: `2401011341` - _**MaBA**_: `N2024000598` _**NgayKCB**_: `18/01/2024` - _**MaPhong**_: `L6` - _**MaDV**_: `01` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH469` - _**PhieuYC**_: `Sổ chẩn đoán hình ảnh`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân chỉ định cls CH469 số lượng 1 khi trả kết quả xong
-> Sổ chẩn đoán bị double dữ liệu bệnh nhân này.

```
trả kết quả Xquang
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/7d7b3fe1-0896-4d61-8a31-707b44e889df)
Sổ chẩn đoán hình ảnh Diag
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/1d690f73-2593-4b46-8f32-0ddf869863b6)
Sổ chẩn đoán hình ảnh Reports
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/3d2ea0b5-2719-4ff2-afbd-53d87a361d33)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240126.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240126zip---26012024)
- File: [HospitalDiagnoseSetup20240126.zip](https://gofile.me/78TQg/fojJj2ctv) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitaldiagnose/blob/main/CHANGELOG.md#file-hospitaldiagnosesetup20240126zip---26012024)

**Comment by le-an-87** [comment]
Đã fix sổ chẩn doán hình ảnh!
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/7d4b5c51-3b05-4e11-abf6-f9256dab4b4c)

* anh cho em hỏi sao lại bỏ chức năng xuất excel khi lick chuột phải rồi anh
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/7617eaf0-480e-43e7-b719-f2ab4ff859fb)

**Comment by le-an-87** [comment]
Ah chắc do hết key bản quyền. sorry anh!

**Comment by le-an-87** [comment]
đã Fix!
