### ISSUE TITLE
Lỗi - Không thay đổi được cls mặc định cho bệnh lý (BV QDY ST)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#55]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lao_st_capcuu_25042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_lao_st_capcuu_25042024`](https://gofile.me/78TQg/UlujdsL4s)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**ma_benh_ly**_: `XQ26`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Diag không thay đổi được cls mặc định cho bệnh lý.
- Khi thay đổi bấm chỉnh hoặc xóa cls mặc định xong thực hiện lưu
-> sau đó tắt Form bệnh lý và mở lại thì không thay đổi.

```
Trước khi chỉnh
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/f56b52c6-5ab6-4f6b-8e31-140a385b4e45)
Chỉnh xóa mã cls mặc định
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/a8facba6-da96-4e03-9671-6e9dd445a1c2)
Tắt Form và vào lại vẫn không thay đổi
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/18e4ea35-e0bb-4f78-8e13-e92ad1f53dd1)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitaldiagnose/55)

**Comment by vinh-dh** [comment]
- File: [HospitalDiagnoseSetup20240426.zip](https://gofile.me/78TQg/fojJj2ctv) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitaldiagnose/blob/main/CHANGELOG.md#file-hospitaldiagnosesetup20240426zip---26042024)

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/0243751f-707b-4fd6-aebb-0b6a6c94b583)
