### ISSUE TITLE
Lỗi - BV Phụ Sản Cần Thơ: mẫu kết quả điện tim theo yêu cầu

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#56]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/5/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_prescription_inbangke_25032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/tTqOkEPfE)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000008` - _**MaKB**_: `2403011559` - _**MaBA**_: `MaBA` _**NgayKCB**_: `20/5/2024` - _**MaPhong**_: `20` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI95` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Mẫu điện tim tự thiết kế hiện tại chưa đáp ứng được yêu cầu của BV Phụ Sản

![319094321-a44daf38-db4c-453e-93a6-a7c3cf6a7bfe](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/f529447f-d395-4b33-a92d-4a4d2af3c329)
![319094389-3a099892-b26c-4887-ac51-b147dce03dc4](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/c286303d-2e34-4c5b-ac6b-2bdef7a5e4bd)

- Theo ý muốn của BV thì hình ảnh điện tim trên phiếu kết quả là hình ảnh thật của bệnh nhân
- BV sẽ tự tạo file hình diện tim của bệnh nhân lưu vào máy , khi trả kết quả thì nhân viên sẽ chọn hình lưu vào phần mềm để in lên phiếu kết quả
-> Hiện tại khi load ảnh điện tim lưu vào phần mềm thì chưa lấy ảnh lên được mẫu in tự thiết kế
- Mẫu yêu cầu có trả kết quả bệnh lý ở trang 1 và các chỉ số điện tim trả kết quả trên trang 2 : hiện tại phần mềm chỉ trả được kết quả mô tả bệnh lý ở trang 1 chưa nhập được các chỉ số điện tim ở trang 2

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/046468bb-f932-4607-a1c5-0069df1eee33)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/29d88cf2-4f55-40c0-a8ea-91ba9ead2ee6)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/4bb144ed-8f1a-454f-a686-01207e617ba8)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/fb5955aa-a6d5-4d76-b7f4-bf04d57e432f)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/2e4b0f23-d22f-43b9-bb72-20d88b7cf579)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0521.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405210-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405210-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405210-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi không thể hiện được hình trên mẫu điện tim tự thiết kế.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/56

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
1. Phần mềm mới đã thêm được ảnh điện tim lên phiếu kết quả điện tim

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/b160e938-7177-4cfc-a3de-9e2b3e5ff7ee)

2. Phần chỉ số điện tim ở trang 2 em chưa tìm được cách nhập (nếu có rồi anh hướng dẫn giúp em) BV muốn nhập lên máy các chỉ số để in lên trang 2. (như nhập mô tả bệnh lý)

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/eb152881-59d3-4479-b390-96c6a74a1245)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/a2ed3438-398f-4129-9cf0-c934cce2a448)

3. Các para hiện tại như:
- 1 số para không hoạt động: cannang, chieucao chưa lấy được thông tin
- Chưa có para huyết áp, ngày giờ trả kết quả (định dạng: ngày giờ phút)

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/91469cc3-7bcb-4648-81a3-7d4ca88e2df5)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/f9afdcc7-af6f-4ac2-b564-c0be33be12b8)

4. Phần lời dặn em không chỉnh về cỡ chữ 11, 12, 13 được chỉ chỉnh được cỡ chữ khoảng 10 hay 14 khi lên trang in cỡ chữ tự thay đổi

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/ad5cb8e0-e995-4802-8dd6-555efa9f36bf)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/679f597b-f483-4a8e-8b7b-ba8fdd6af5a0)

**Comment by vinh-dh** [comment]
2. Nó chính là thông tin hành chánh và mô tả bệnh lý ở trang 1 đó. Tại cái máy điện tim nó in ra mẫu kq của nó, BV muốn có nó thì xuất nó dạng ảnh chung với tín hiệu luôn là ok chứ gì.
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/209125c9-005f-492d-b0d3-fda01c7f14c1)

3. Để a kiểm tra lại.
4. Nó là ô RichText, nên trên tự thiết kế cũng phải chọn kiểu của nó là RichText

**Comment by chauthanhtra** [comment]
2. Để em hỏi xem BV chịu xuất dạng file ảnh không

4. Đã chọn kiểu Richtext rồi anh nhưng cõ chữ vẫn in ra không đúng . nó tự thay đổi cỡ chữ

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/073b3a5b-4fa8-4e42-8718-197c8cce7204)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0521.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405212-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405212-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405212-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi thiếu dữ liệu thông tin para cannang và chieucao trên mẫu điện tim tự thiết kế.

- 🐛: Sửa lỗi para Lời dặn/đề nghị mất cỡ chữ trên mẫu điện tim tự thiết kế.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/56

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by vinh-dh** [comment]
Còn ngày kết quả thì chuỗi theo chuẩn quy định:
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/0d3ed7ed-aeae-4b72-8c8f-67a5a50bfc11)

Với lại DevExpress không hỗ trợ para kiểu ngày giờ:
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/9db2b1a6-1561-4e35-9865-f60e427683d9)

**Comment by ongtrieuhau-dh** [comment]
Cái này anh @vinh-dh tạo thêm các para  để đáp ứng đa số yêu cầu của bệnh viện và tận dụng triệt tính chất tự thiết kế cho khách hàng nhé a 
- Para thể hiện ngày giờ in theo chuẩn DHG 
- 06 para ngày giờ (dd, MM, yyyy, HH, mm, ss) dưới dạng string (nếu chưa có)
- Para Địa phương lấy trên tham số hệ thống (nếu chưa có)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0523.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405230-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405230-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405230-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Bổ sung các tham số trên mẫu điện tim tự thiết kế, gồm: `ngaykq_ngay, ngaykq_thang, ngaykq_nam, ngaykq_gio, ngaykq_phut, ngaykq_giay` và `diaphuong`.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/56#issuecomment-2122486771

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
> ### 📣📣📣 Diagnose.exe v.3.24.0523.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405230-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405230-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405230-NasDHSolutions.json)
> ## Nội dung thay đổi
> 
>     * ✨: Bổ sung các tham số trên mẫu điện tim tự thiết kế, gồm: `ngaykq_ngay, ngaykq_thang, ngaykq_nam, ngaykq_gio, ngaykq_phut, ngaykq_giay` và `diaphuong`.
> 
>     * ☑: [Lỗi - BV Phụ Sản Cần Thơ: mẫu kết quả điện tim theo yêu cầu #56 (comment)](https://github.com/dh-hos/dhg.hospitaldiagnose/issues/56#issuecomment-2122486771)
> 
> 
> [![](https://camo.githubusercontent.com/58ed67fda215f8fdefd84e02cb5453030678d78c058aaad1b5e9f04f3089c602/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d54682545312542422542316325323068692545312542422538376e253230622545312542422539466925334125323025343076696e682d2d64682d696e666f726d6174696f6e616c3f6c6f676f3d676974687562)](https://github.com/vinh-dh) [![](https://camo.githubusercontent.com/8375d1042897ab92159f8fc4de5d61a4a3b7586baa3d15442c948f68a357f76c/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d58656d2532306c2545312542422538426368253230732545312542422541442532307068692543332541416e253230622545312542412541336e2d696e666f726d6174696f6e616c3f6c6f676f3d676974687562)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://camo.githubusercontent.com/d21df0e2392d69e70bbbda45fa7304196e57abd1cfa17878b66b0b728a485153/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4e682545312542412541446e25323074682543332542346e67253230622543332541316f25323074722543332541416e25323054656c656772616d2d3243413545303f7374796c653d666c61742d73717565617265266c6f676f3d74656c656772616d266c6f676f436f6c6f723d7768697465)](https://t.me/dhhoscodemsifiles)

- Phần ngày giờ đã đáp ứng được mẫu yêu cầu BV

- BV đã chấp nhận lấy ảnh thay cho phần nhập chỉ số ở trang 2

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/d6aec3cd-d7a7-4d39-8418-e767f8ceb9a0)

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/e4ef66b9-7a02-402c-8ed3-4da9976c657d)


- Mẫu mới còn thiếu para Huyết áp nha anh. anh bổ sung thêm para huyết áp giúp em
> Các para hiện tại như:
  >  para cannang, chieucao, ngày giờ trả kết quả (định dạng: ngày giờ phút) đã lấy được thông tin
   > Chưa có para huyết áp, 


![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/b1f69b99-ddd6-4b4a-ae23-4689aac3accb)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/90d7b0f6-57f3-4b61-b713-63bfccb8112a)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0531.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405311-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405311-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405311-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Bổ sung tham số chỉ số huyết áp `huyetap` cho phiếu điện tim tự thiết kế.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/56

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
> ### 📣📣📣 Diagnose.exe v.3.24.0531.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405311-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405311-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32405311-NasDHSolutions.json)
> ## Nội dung thay đổi
> 
>     * ✨: Bổ sung tham số chỉ số huyết áp `huyetap` cho phiếu điện tim tự thiết kế.
> 
>     * ☑: [Lỗi - BV Phụ Sản Cần Thơ: mẫu kết quả điện tim theo yêu cầu #56](https://github.com/dh-hos/dhg.hospitaldiagnose/issues/56)
> 
> 
> [![](https://camo.githubusercontent.com/58ed67fda215f8fdefd84e02cb5453030678d78c058aaad1b5e9f04f3089c602/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d54682545312542422542316325323068692545312542422538376e253230622545312542422539466925334125323025343076696e682d2d64682d696e666f726d6174696f6e616c3f6c6f676f3d676974687562)](https://github.com/vinh-dh) [![](https://camo.githubusercontent.com/8375d1042897ab92159f8fc4de5d61a4a3b7586baa3d15442c948f68a357f76c/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d58656d2532306c2545312542422538426368253230732545312542422541442532307068692543332541416e253230622545312542412541336e2d696e666f726d6174696f6e616c3f6c6f676f3d676974687562)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://camo.githubusercontent.com/d21df0e2392d69e70bbbda45fa7304196e57abd1cfa17878b66b0b728a485153/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4e682545312542412541446e25323074682543332542346e67253230622543332541316f25323074722543332541416e25323054656c656772616d2d3243413545303f7374796c653d666c61742d73717565617265266c6f676f3d74656c656772616d266c6f676f436f6c6f723d7768697465)](https://t.me/dhhoscodemsifiles)

Diagnose mới đã bổ sung para huyết áp 

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/68eb9be9-591b-4046-96ef-aefe89307192)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/47b0c317-f644-4260-bfb6-4eb119cc5c63)

**Comment by chauthanhtra** [comment]
BV đã xác nhận mẫu Điện Tim mới theo yêu cầu hoàn thành

![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/106cdc40-da59-4e38-b854-66394787c2a5)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/65467361-5fa6-4e3c-8e6b-5c05c3374b96)
