### ISSUE TITLE
Lỗi - Mẫu tự thiết kế Nội soi TMH không lấy được 6 hình (BV Tâm Phúc)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#57]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_nstmh_25062024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_tamphuc_nstmh_25062024`](https://gofile.me/78TQg/VRoCuQRLS)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023012295` - _**MaKB**_: `2406006743` - _**NgayKCB**_: `25/06/2024` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SO72` - _**PhieuYC**_: `Kết quả nội soi TMH tự thiết kế`

### Mẫu Nội soi TMH tự thiết kế
> 1. Khi load mẫu mặc định có 6 para hình ảnh từ 1 đến 6 -> khi lưu xong vào xem lại chỉ còn 4 para hình ảnh từ 1 đến 4.
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/45194c05-0e49-4ffe-8bad-c5017615ae6f)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/5dc78e68-b9c4-4237-9fcb-a79748989f1f)
***
> 2. chỉ có 4 para mota từ 1 đến 4 (para mô tả hình ảnh)
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/6b1e3371-29e2-4dd6-aa2d-beb5c00c55dc)

## Lỗi dẫn đến không thiết kế được mẫu kết quả có 6 hình ảnh.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0626.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32406261-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32406261-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32406261-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi mẫu tự thiết kế Nội soi TMH không lấy được 6 hình.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/57

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix lỗi para hình ảnh
Đã bổ sung para mô tả 5 6

> para mô tả nọi soi tai mũi hông 3 4 5 6 không lấy được nội dung
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/b244be0d-e63f-46e6-a9ae-4b91852e3263)
> para mô tả nội soi không lấy được nội dung
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/f45da085-fd0c-4bba-be35-f4a6cd33cc4a)

**Comment by vinh-dh** [comment]
> para mô tả nọi soi tai mũi hông 3 4 5 6 không lấy được nội dung

Vì nội soi TMH không có ô nhập cho các mô tả này, nên không có là đúng rồi. Các para đó là sử dụng chung với các mẫu, nên nó có theo thôi.

**Comment by le-an-87** [comment]
Ok vậy mẫu nội soi không có sử dụng para mota hé anh.
em close git lại.
