### ISSUE TITLE
Lỗi - Mẫu trả kết quả CLS Siêu Âm tự thiết kế thiếu Para QRCode thông tin bệnh nhân CLS của BV Phụ Sản CT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#58]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **3/7/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_130`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/DTbUUotaL)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024035255` - _**MaKB**_: `2405000177` - _**MaBA**_: `MaBA` _**NgayKCB**_: `3/7/2024` - _**MaPhong**_: `17` - _**MaDV**_: `10` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI42` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Mẫu tự thiết kế phiếu kết quả Siêu âm thiếu Para QRCode thông tin bệnh nhân và thông tin trả kết quả CLS

- Mẫu cũ
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/d1d3a0fe-3d8c-44a2-bd72-f7b106122f68)

- Mẫu tự thiết kế
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272332/da97641d-ec6c-481d-9a31-548f47eb0f48)

**Comment by vinh-dh** [comment]
Để anh kiểm tra.

**Comment by vinh-dh** [comment]
Đây không phải lỗi. Phiếu Siêu âm Bệnh viện Phụ Sản đang sử dụng cột chukybschidinh làm QRCode.
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/a56c8285-e704-4548-8319-3d52ee5fb942)

![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/9a71f82a-ab9e-4a67-bb15-1e3c177ee234)

**Comment by chauthanhtra** [comment]
Dạ . ok anh. để em báo BV
