### ISSUE TITLE
Lỗi - TREO MÁY KHI LƯU KẾT QUẢ SIÊU ÂM

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitaldiagnose#59]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `70082`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA 123 HÙNG VƯƠNG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_123hv_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

PK 123 Hùng Vương lưu kết quả đến bước "Cập nhật dữ liệu" thì treo không thể lưu kết quả 
chỉ lưu được khi đăng nhập tài khoản bskhue và admin
quá trình test khi restore tại Cty thì ngoài tài khoản bskhue và admin thì các tài khoản khác lưu cũng khá chậm 
còn ở tại đơn vị em test thì ngoài 2 tài khoản như trên thì lưu kết quả đều treo.

em đã  : 
- chạy hết cấu trúc trên admin
- thực hiện test trên bảng v3.24.0626.1
- cập nhật đầy đủ danh mục theo 4750
- add các tài khoản liên quan vào nhóm admin như 2 tài khoản trên 
- kiểm tra danh mục nhân viên không có lưu dữ liệu bất thường
- siêu âm không lưu hình ảnh nên không liên quan đến đường dẫn
- khi chọn mô tả em bỏ trống vẫn bị tình trạng treo
- cập nhật bản cũ hơn trong tháng 06 vẫn bị
- câp nhật bản cũ cuối 2023 bị lỗi cấu trúc

>> hiện không thể hoạt động phòng siêu âm. >> hỗ trợ dùm em chổ này vì không xác định được nguyên nhân

![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/130281806/3adefc8f-b462-492a-895c-a76aa9441a3b)
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/130281806/8949c626-ff13-4f67-afdd-c52ffa0d135c)

[Clip test tài khoản](https://gofile.me/78TQg/f4tofNrVd)

**Comment by vinh-dh** [comment]
Để a coi.

**Comment by nqhoa1005** [comment]
Em thực hiện test trên dữ liệu restore thì tài khoản khác lưu 10-15s vẫn lưu đc kết quả và show trang in, còn tại đơn vị thì bị treo

**Comment by nqhoa1005** [comment]
anydesk máy chủ :
310472581
pass : Admin@333

**Comment by vinh-dh** [comment]
Em hỏi phòng khám coi sao phải thay đổi tham số `folderimage `vậy? Không có giá trị thì phần mềm nó dò không thấy là sẽ treo.

![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/112069710/8b2fbd94-7e41-451d-86ac-31ce3b1dfef4)

**Comment by vinh-dh** [comment]
Em test trên máy chủ cty có bị chậm ko? Anh test không bị chậm.

**Comment by nqhoa1005** [comment]
test dữ liệu đã restore các tài khoản khác vẫn chậm khoảng 10-15s
hiện tại phòng khám là cứ treo tại chổ đó

**Comment by vinh-dh** [comment]
Cụ thể tài khoản nào chậm, em cung cấp anh test thử.

**Comment by nqhoa1005** [comment]
2 tài khoản này anh
bslan
bsanhtuyet

**Comment by vinh-dh** [comment]
> bslan

Để a thử

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0704.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407040-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407040-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407040-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Thực hiện bổ sung ngày thực hiện y lệnh CĐHA #21.

- ✨: Sửa lỗi - TREO MÁY KHI LƯU KẾT QUẢ SIÊU ÂM #59.

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/21

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/59

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
Đã fix lỗi không còn treo máy
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/130281806/a43faa99-f671-41e8-9734-bf3fff795433)
