### ISSUE TITLE
Yêu cầu - bổ sung ghi nhận nhật ký và tìm kiếm

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#6]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_ketquadt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
1. Khi ghi nhận nhật ký Diagnose đề nghị bổ sung thêm mã Bệnh nhân, mã Khám bệnh và mã Bệnh án đối với bệnh nhân nội trú
để dễ kiểm tra và đối chiếu.

2. Bổ sung tìm kiếm theo nội dung có trong dữ liệu.

```
1. Hiện tại có 1 số nhật ký chỉ có tên bệnh nhân và mã kb thôi
![image](https://user-images.githubusercontent.com/96155021/191654215-060f31d1-c308-4e85-b15d-90e741efe050.png)

2. Chức năng tìm kiếm chỉ tìm kiếm chính xác hoặc nội dung bắt đầu
![image](https://user-images.githubusercontent.com/96155021/191654323-b6b26b65-cd69-4503-b015-4c84ec57a8d7.png)

tìm kiếm trong nội dung thì không được (tìm tên theo hình trên thì phần mềm không tìm thấy)
![image](https://user-images.githubusercontent.com/96155021/191654398-696a1cc1-eda4-4651-b0a3-889c445852b2.png)

**Comment by vinh-dh** [comment]
1. Anh sẽ bổ sung makb vào nội dung khi ghi nhận nhật ký chỉnh kết quả (có makb thì sẽ biết mabn và maba).
2. Form theo dõi nhật ký này là sử dụng chung từ LibraryApp.dll (@ongtrieuhau đang phụ trách code). Cụ thể: `private LibraryApp.FrmNhatKyThaoTac objFrmNhatKyThaoTac;`. Do đó đề nghị tìm kiếm theo cột nội dung này em liên hệ @ongtrieuhau nhé!

**Comment by le-an-87** [comment]
1. anh bổ sung thêm mabn, maba luôn được không anh
Trường hợp nội trú nó dựa theo maba mà cái đó lưu makb không cũng khó kiểm tra

**Comment by le-an-87** [comment]
đã bổ sung mabn, makb, maba vào nhật ký!
