### ISSUE TITLE
Lỗi - Sổ chẩn đoán hình ảnh mất chức năng lập Ekipt (BV Phụ sản - 92118)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitaldiagnose#60]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_socdha_11072024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_socdha_11072024`](https://gofile.me/78TQg/evKUxPHnw)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024050897` - _**MaKB**_: `2406014775` - _**MaBA**_: `010379` _**NgayKCB**_: `25/06/2024` - _**MaPhong**_: `45` - _**MaDV**_: `22` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH419` - _**PhieuYC**_: `Sổ chẩn đoán hình ảnh`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Sổ chẩn đoán hình ảnh mất chức năng thêm ekipt

```
>Chức năng lập ekip Diag phiên bản củ
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/cba1b17c-577f-4d43-a881-e2bd784839b7)

>Diag và Reports mới không có chức năng này
![ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/96155021/a161b24b-e10f-4b13-858c-d3ef2cadaca6)

**Comment by vinh-dh** [comment]
Để anh kiểm tra.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0711.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407110-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407110-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407110-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi `Sổ chẩn đoán hình ảnh` mất chức năng lập Ekipt (BV Phụ sản - `92118`).

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/60

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
anh cho em hỏi lý do sao phải cấu hình mã loại PT/TT nữa anh
![ảnh](https://github.com/user-attachments/assets/4022afbc-884f-441a-830d-442cef1644f3)

**Comment by vinh-dh** [comment]
[Mã loại PT] chỗ này phục vụ cho báo cáo chi phí TT/PT ekip.
