### ISSUE TITLE
Lỗi - Diagnose Phiếu kết quả điện tim không hiển thị được hình ảnh đã chọn 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitaldiagnose#61]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `All`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphuoclong_052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/9iq7KNk7z)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024010363` - _**MaKB**_: `2405011841` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/07/2024` - _**MaPhong**_: `00` - _**MaDV**_: `02` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
   > _**MaCLS**_: `DI184` - _**PhieuYC**_: `PhieuYC`

Phiếu kết quả điện tim tự thiết kế có chọn Ảnh nhưng khi lên mẫu chưa hiển thị được hình ảnh như hình dưới
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272364/922f3752-5a6f-4d4d-bc0c-b8514af1d932)

Mẫu thiết kế
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272364/b31a70dc-ad0c-41d5-9f28-199a8ab210ab)
Phiếu kết quả
![image](https://github.com/dh-hos/dhg.hospitaldiagnose/assets/97272364/e0e1e482-2e69-40dd-a9d3-d0d5cc25f04f)

**Comment by vinh-dh** [comment]
Để anh kiểm tra

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0712.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407120-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407120-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32407120-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi phiếu kết quả điện tim không hiển thị được hình ảnh đã chọn.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/61

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã ok rồi á
![image](https://github.com/user-attachments/assets/ddd500ce-3b8a-4379-b497-f3a9c486d3e6)
