### ISSUE TITLE
Lỗi - Diagnose mới load bệnh lý có cấu hình CLS đã ngưng sử dụng 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#67]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_loifont_motabenhly_29082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `9434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Zb6momfIq)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Diagnose mới phần Bệnh lý hiển thị các bệnh lý có cấu hình CLS mặc định đã ngưng sử dụng hoặc đã xóa nhưng phần mô tả bệnh lý và chi tiết mô tả bệnh lý thì không có thông tin các bệnh lý đó
-> Cần thống nhất lại cách lấy bệnh lý, mô tả bệnh lý, chi tiết mô tả bệnh lý

- Phần mềm Diagnose cũ không load bệnh lý có cấu hình CLS đã xóa, ngưng sử dụng

![ảnh](https://github.com/user-attachments/assets/99d3e02a-e345-4a51-a7a3-5623c2d51a46)
![ảnh](https://github.com/user-attachments/assets/6e300485-2a7b-4ad2-b540-06ac80d12026)
![ảnh](https://github.com/user-attachments/assets/b1b5fca2-123d-48cc-a596-e0ec19788541)

-  Phần mềm Diagnose mới load bệnh lý có cấu hình CLS đã xóa, ngưng sử dụng nhưng mô tả bệnh lý và chi tiết mô tả bệnh lý thì không thấy bệnh lý đó

![](https://i.imgur.com/keD1gZH.png)
![](https://i.imgur.com/SGewdr5.png)
![](https://i.imgur.com/ll6Tff8.png)

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
👉 Xử lý: 
- Phải hiển thị các bệnh lý, mô tả bệnh lý, chi tiết mô tả bệnh lý: vì không hiển thị thì khi người dùng quay lại các ca cũ (CLS lúc trước chưa xóa) để điều chỉnh thì không có dữ liệu để thực hiện.
- Các mô tả bệnh lý và chi tiết mô tả bệnh lý không hiển thị đầy đủ: để anh kiểm tra lại.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0918.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409180-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409180-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409180-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi load thiếu bệnh lý đối với danh mục mô tả bệnh lý. ![image](https://github.com/user-attachments/assets/df15fab3-ffa9-45e6-bc12-8ae40cfe6b46)

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/67

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '25/9/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.0918.0
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Mô tả bệnh lý đã thể hiênh đủ bệnh lý

- Hình ảnh: 

![](https://i.imgur.com/zgPEtij.png)

***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi:

  - Chi tiết mô tả bệnh lý vẫn không thể hiện đủ bệnh lý có mô tả bệnh lý

- Hình ảnh lỗi:

![](https://i.imgur.com/z1cGrcN.png)

> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by vinh-dh** [comment]
>   - Chi tiết mô tả bệnh lý vẫn không thể hiện đủ bệnh lý có mô tả bệnh lý
Để anh kiểm tra.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0920.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409200-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409200-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409200-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi: Load thiếu bệnh lý tại form [Chi tiết mô tả bệnh lý].

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/67

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm  Diagnose.exe v.3.24.0920.0
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Đã fix thiếu Bệnh lý ở chi tiết mô tả bệnh lý

- Hình ảnh: 

![](https://i.imgur.com/DH3lMoz.png)
![](https://i.imgur.com/lCLpA5l.png)
![](https://i.imgur.com/PZY6TUJ.png)

***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi:

  - Bênhk lý không có cấu hình CLS mặc định không hiển thị trên form chọn bệnh lý khi trả kết quả CLS

- Hình ảnh lỗi:

![](https://i.imgur.com/OJBukjs.png)
![](https://i.imgur.com/wzDNpX5.png)
![](https://i.imgur.com/aW0vO18.png)
![](https://i.imgur.com/cnZJZkY.png)

> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu, phát hiện lỗi mới
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by vinh-dh** [comment]
Để anh kiểm tra tiếp.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0920.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409201-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409201-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409201-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi: các form thực hiện cận lâm sàng load thiếu bệnh lý.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/67

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.0920.2
***
>

> Lỗi, yêu cầu đã hoàn thành 
> 
> - Nội dung: 
> 
>   - 
> 
> - Hình ảnh: 
> 

***

> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi:
  - Diagnose mới báo lỗi khi vào chẩn đoán CLS
  -  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2408008778` - _**MaBA**_: `MaBA` _**NgayKCB**_: `20/09/2024` - _**MaPhong**_: `10` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
- Hình ảnh lỗi:

![](https://i.imgur.com/JUuNayl.png)
![](https://i.imgur.com/lxml5F2.png)
![](https://i.imgur.com/e9PGzRo.png)

> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by vinh-dh** [comment]
![image](https://github.com/user-attachments/assets/2d7b04e2-f0c6-4b75-b7e7-111296d40685)

Thì ra cái này build bị lỗi anh không hay. Để anh build lại.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0923.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409230-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409230-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409230-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi: mất chức năng lập phiếu thủ thuật BV Tim Mạch CT.

- 🐛: Sửa lỗi: các form thực hiện cận lâm sàng load thiếu bệnh lý.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/68

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/67

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '29/9/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.0923.0
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Diagnose mới đã fix lỗi danh mục không hiển thị hết bệnh lý, mô tả bệnh lý, chi tiết mô tả bệnh lý
  - Đã fix lỗi form chẩn đoán không lấy hết danh mục bệnh lý không cấu hình CLS mặc định hoặc cấu hình CLS mặc định đã ngưng sử dụng 
  - Đã fix lỗi trả kết quả CLS 

- Hình ảnh: 

  - Ảnh Danh mục
  - ![](https://i.imgur.com/ipXPUlr.png)
  - ![](https://i.imgur.com/O6NlBin.png)
  - ![](https://i.imgur.com/cvMk4Bi.png)

  - Ảnh bệnh lý form chẩn đoán
  - ![](https://i.imgur.com/IUpa1Gh.png)
  - ![](https://i.imgur.com/tKlrXYZ.png)

  - Ảnh trả kết quả CLS
  - ![](https://i.imgur.com/wlAEYUV.png)
  - ![](https://i.imgur.com/KdRslg0.png)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

> - Diễn giải lỗi:
>   - 
> 
> - Hình ảnh lỗi:
> 


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
