### ISSUE TITLE
Lỗi - Diagnose mới mất chức năng lập phiếu thủ thuật

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#68]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_ct_dia_phieutt_hinhsieuam_18092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6AOtK8TX3)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `19013255` - _**MaKB**_: `2409012806` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/9/2024` - _**MaPhong**_: `09` - _**MaDV**_: `01` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `S05` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phần mềm Diagnose mới không tìm thấy chức năng lập phiếu thủ thuật

- Phần mềm Diagnose cũ có chức năng lập phiếu thủ thuật

![](https://i.imgur.com/1dBttI9.png)

- Phần mềm Diagnose mới không thấy chức năng lập phiếu thủ thuật

![](https://i.imgur.com/ApUTBv9.png)

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
👉 Để anh kiểm tra.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0920.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409202-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409202-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409202-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi: mất chức năng lập phiếu thủ thuật BV Tim Mạch CT.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/68

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.0920.2
***
>Lỗi, yêu cầu đã hoàn thành 

> 
> - Nội dung: 
> 
>   - 
> 
> - Hình ảnh: 
> 
> 

***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.


- Diễn giải lỗi:
  - Diagnose mới vẫn chưa có chức năng lập phiếu thủ thuật

- Hình ảnh lỗi:

![](https://i.imgur.com/wwqX45X.png)


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by vinh-dh** [comment]
Để anh kiểm tra lại.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0923.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409230-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409230-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409230-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi: mất chức năng lập phiếu thủ thuật BV Tim Mạch CT.

- 🐛: Sửa lỗi: các form thực hiện cận lâm sàng load thiếu bệnh lý.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/68

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/67

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '29/9/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.0923.0
***
>Lỗi, yêu cầu đã hoàn thành 

> 
> - Nội dung: 
> 
>   - 
> 
> - Hình ảnh: 
> 
> 

***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.


- Diễn giải lỗi:
  - Phần mềm Diagnose mới có chức năng lập phiếu TT nhưng còn lỗi
  - Không hiện mã loại TT ở cột TT/PT
  - Form lập phiếu có 2 thông tin ngày giờ chưa xác định
  - Lập phiếu xong thì hiện form nhập thông tin mà không phải trang in phiếu
  - Lập phiếu xong bấm chỉnh thì báo tài khoản đang sử dụng không phải tài khoản lập phiếu không cho chỉnh

- Hình ảnh lỗi:

![](https://i.imgur.com/cow5Us1.png)
![](https://i.imgur.com/ZV1O9av.png)
![](https://i.imgur.com/tJECMLE.png)


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by vinh-dh** [comment]
Để a kiểm tra tiếp.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0926.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409260-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409260-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409260-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi thực hiện Thủ thuật/Phẫu thuật.

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/68

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '30/9/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.0926.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Diagnose mới đã lập được phiếu thử thuật, có hiện mã loại CLS vào ô TT/PT, lưu phiếu TT hiện trang in

- Hình ảnh: 

![](https://i.imgur.com/WD869fx.png)

***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Lập phiếu xong lưu lại đóng các trang in thì bấm chỉnh sẽ báo lỗi không phải người thực hiện phải đóng form mở lại mới chỉnh được
  - Không hiển thị tiền công ekip PT/TT phải đóng form mở lại bấm chỉnh phiếu, chọn nhân viên ekip bấm chỉnh ekip rồi lưu lại mới có tiền công
  - Có 1 số thông tin khi bấm chỉnh phiếu thì không chỉnh được như ngày rút chỉ, ngày cắt chỉ, mã máy thựu hiện TT/PT

- Hình ảnh lỗi: Clip ghi nhận lỗi

https://gofile.me/78TQg/EH0eGqicF


***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by vinh-dh** [comment]
Để anh kiểm tra tiếp.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.0930.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409300-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409300-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32409300-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa các lỗi tổng hợp phiếu TT/PT. ![image](https://github.com/user-attachments/assets/56ff022e-af64-48f9-89d1-a9778429cb96)

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/68

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '7/10/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.0930.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Đã fix lỗi lập phiếu xong lưu lại đóng các trang in thì bấm chỉnh sẽ báo lỗi không phải người thực hiện phải đóng form mở lại mới chỉnh được
  - Đã fix lỗi có 1 số thông tin khi bấm chỉnh phiếu thì không chỉnh được như ngày rút chỉ, ngày cắt chỉ, mã máy thựu hiện TT/PT

- Hình ảnh: 

![](https://i.imgur.com/T8H2P5Q.png)

***
### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Không hiển thị tiền công ekip PT/TT phải đóng form mở lại bấm chỉnh phiếu, chọn nhân viên ekip bấm chỉnh ekip rồi lưu lại mới có tiền công
  - Đề xuất: Hiện tại ở form danh sách bệnh nhân CLS nào có cấu hình loại TT/PT . nếu có thực hiện lập phiếu TT/PT rồi thì check vào ô có TT/PT. người dùng không phân biệt được CLS nào cần phải lập phiếu -> Đề xuất: Chỉ CLS có cấu hình loại PT/TT thì mới có mã loại CLS ở cột TT/PT không có thì để trống để người dùng dễ sử dụng 
- Hình ảnh lỗi:

![](https://i.imgur.com/jP9RSrV.png)

![ảnh](https://github.com/user-attachments/assets/650d6c09-3b26-475b-95af-b0dbc1e9b728)


***

Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
>   - Không hiển thị tiền công ekip PT/TT phải đóng form mở lại bấm chỉnh phiếu, chọn nhân viên ekip bấm chỉnh ekip rồi lưu lại mới có tiền công


Trường hợp này để em test lại sao lúc nảy em thêm không có giờ thêm lại thì có tiền công rồi

**Comment by chauthanhtra** [comment]
> > * Không hiển thị tiền công ekip PT/TT phải đóng form mở lại bấm chỉnh phiếu, chọn nhân viên ekip bấm chỉnh ekip rồi lưu lại mới có tiền công
> 
> Trường hợp này để em test lại sao lúc nảy em thêm không có giờ thêm lại thì có tiền công rồi

- Phần mềm đã lấy được tiền công khi thêm ekip TT/PT
![](https://i.imgur.com/fAAD4oc.png)


- Đề Xuất : khóa các nút Thêm Chỉnh Xóa của Ekip khi chưa bấm chỉnh phiếu. Hiện tại khi người dùng mới lưu phiếu hoặc bấm chỉnh rồi lưu phiếu thì các nút Thêm Chỉnh Xóa của ekip không bị ẩn người dùng có thể thao tác được trên các nút này làm thay đổi dữ liệu trên form nhưng không lưu vào dữ liệu khi đóng form mở lại thì mất -> Khóa các chức năng này khi chưa bấm Chỉnh phiếu để tránh gây ngầm lẫn đã chỉnh được phiếu
![](https://i.imgur.com/9MQCg3E.png)
![](https://i.imgur.com/gTtN2iR.png)

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.1001.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: Phần mềm mới đã fix lỗi

  - Không hiển thị tiền công ekip PT/TT tại form lập phiếu TT/PT
  - Không khóa các nút thêm nhân viên thực hiện Ekip TT/PT sau khi lập xong phiếu TT/PT
  - Chỉ hiển thị mã loại TT/PT ở ở CLS có cấu hình loại PT/TT

- Hình ảnh: 

![](https://i.imgur.com/BDZBW0Z.png)
![](https://i.imgur.com/xA6ZUlM.png)
![](https://i.imgur.com/SvAcBL6.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
