### ISSUE TITLE
Lỗi - Mất Menu Tool chỉnh định dạng font chữ khi sử dụng Mô tả bệnh lý (không chỉnh được định dạng kết luận và lời dặn)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitaldiagnose#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_dinhdangpara_ketluan_dia_10102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/fgOiOJYcj)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023012880` - _**MaKB**_: `2410003510` - _**MaBA**_: `MaBA` _**NgayKCB**_: `10/10/2024` - _**MaPhong**_: `06` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI08` - _**PhieuYC**_: `PhieuYC`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi sử dụng tham số ha.sudungmotabenhly = 1 thì form bệnh lý và form chẩn đoán mất Menu Tool chỉnh định dạng font chữ. BV không chỉnh được định dạng font chữ cho lời dặn và kết luận  (bản in phiếu kết quả không chỉnh được định dạng chữ cho dữ liệu dạng RichText khi thiết kế mà phải chỉnh trong bệnh lý hoặc form trả kết quả)
-> Lấy lại menu tool định dạng font chữ

- Ảnh khi có menu tool chỉnh định dạng font khi tham số ha.sudungmotabenhly = 0 hoặc 2

![](https://i.imgur.com/N4lRERV.png)
![](https://i.imgur.com/uH48ulp.png)

- Ảnh khi không có menu tool chỉnh định dạng font khi tham số ha.sudungmotabenhly = 1

![](https://i.imgur.com/E0QHzEq.png)
![](https://i.imgur.com/2derVgi.png)
![](https://i.imgur.com/tHJG1dC.png)

**Comment by vinh-dh** [comment]
Để anh kiểm tra lại.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Diagnose.exe v.3.24.1014.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32410140-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32410140-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDiagnoseexe%2F32410140-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Sửa lỗi: Mất Menu Tool chỉnh định dạng font chữ khi sử dụng Mô tả bệnh lý (không chỉnh được định dạng kết luận và lời dặn). ![image](https://github.com/user-attachments/assets/7e675c9c-26f4-4f8c-8673-7cc02f4278b1)

- ☑: https://github.com/dh-hos/dhg.hospitaldiagnose/issues/69

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Diagnose.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '22/10/2024'.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.1014.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Form chẩn đoán đã có menu tool chỉnh định dạng font chữ và phiếu kết quả đã in được kết luận và lời dặn theo định dạng chữ đã chỉnh

- Hình ảnh: 

![](https://i.imgur.com/VYPHDsk.png)
![](https://i.imgur.com/93M25Ob.png)

***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Form bệnh lý chưa có menu tool chỉnh định dạng chữ cho kết luận và lời dặn mặc định ( Cần có chức năng này để BV chỉnh định dạng chữ mặc định không phải chỉnh từng bệnh nhân khi trả kết quả)
- Hình ảnh lỗi:
![](https://i.imgur.com/xjB1rKl.png)


***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by vinh-dh** [comment]
Để anh kiểm tra lại chỗ danh mục bệnh lý.

**Comment by vinh-dh** [comment]
@chauthanhtra chờ server upload được anh upload sau nhé!

**Comment by vinh-dh** [comment]
Đã chuyển sang git mới: [Lỗi - Mất Menu Tool chỉnh định dạng font chữ khi sử dụng Mô tả bệnh lý (không chỉnh được định dạng kết luận và lời dặn) #9](https://github.com/dh-his/Ghi_Nhan_Loi/issues/9)
