### ISSUE TITLE
Yêu cầu -  Bổ sung chức năng xuất excel dạng dữ liệu

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitaldiagnose#7]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/09/2022**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bổ sung chức năng xuất excel dữ liệu từ lưới sổ chẩn đoán:
![image](https://user-images.githubusercontent.com/91751241/192240156-07e3aa3f-9b76-48e2-9783-4cc336d60fa6.png)
Thêm các cột dữ liệu: mabn, makb, maba, macls, dienthoai.
Để các đơn vị có thể tùy biến các báo cáo khi cần.

```

**Comment by vinh-dh** [comment]
[Diagnose 27/09/2022](https://www.fshare.vn/file/NERC4BZQFMN4)

**Comment by lqbinh1987** [comment]
Chắn năng xuất excel đã ok, nhưng chức năng Xuất excel (dữ liệu) đề nghị xuất theo lưới luông, vì khi có lọc chọn lại sổ phía dưới thì khi xuất Xuất excel (dữ liệu) là nó xuất toàn bộ luôn, chứ không theo cái đã chọn lọc. Vì khi xuất dữ liệu của 1 tháng rất nhiều, khi đó lọc bằng excel cũng rất mất thời gian.
Như hình phía dưới, mặc dù chỉ chọn là XQ kỹ thuật số nhưng khi xuất ra là ra hết luôn.

![image](https://user-images.githubusercontent.com/99630883/192715640-73801274-38a3-4639-aa67-f3d2ff7b7447.png)
![image](https://user-images.githubusercontent.com/99630883/192727028-10c2c05c-56a0-43e5-a59b-8b0d859d8ad0.png)

**Comment by vinh-dh** [comment]
Chức năng click phải xuất Excel này là từ thư viện [Ctrl.dll](https://github.com/dh-hos/oLibraries/blob/main/Ctrl.dll), anh không có code. Em hỏi @nghivanbi nhé!

**Comment by nghivanbi** [comment]
Hỗ trợ xuất vậy đc rồi
