### ISSUE TITLE
Yêu cầu - Bổ sung tiêu chí lấy báo cáo sổ chẩn đoán hình ảnh.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitaldiagnose#9]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87044`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_qdydt_socdha`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`[Tải về tại đây]`](https://drive.google.com/file/d/1sx9HxBRXfp4mRyFNDGvX58pA1Mf5_fjM/view?usp=sharing)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu trong sổ chẩn đoán hình ảnh bổ sung thêm cột để lọc những BN thuộc Thu phí và BHYT không thanh, là những cls thuộc diện BN phải đóng tiền 100%.

**Comment by vinh-dh** [comment]
Y/c này chỉ áp riêng cho QDY Đồng Tháp thôi phải không @lqbinh1987 ?

**Comment by vinh-dh** [comment]
[Diagnose 20/10/2022](https://www.fshare.vn/file/D8OJCUXT3NQJ)
